# https://rainboard.laas.fr/project/example-adder/.gitlab-ci.yml

variables:
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"

cache:
  paths:
    - ccache

.robotpkg-example-adder: &robotpkg-example-adder
  retry:
    max: 2
    when: runner_system_failure
  except:
    - gh-pages
  script:
    - mkdir -p ccache
    - echo "CCACHE_DIR=${CI_PROJECT_DIR}/ccache" >> /opt/openrobots/etc/robotpkg.conf

    - cd /root/robotpkg/wip
    - git pull
    - cd example-adder
    - make checkout MASTER_REPOSITORY="git ${CI_PROJECT_DIR}/.git"
    - make install
    - build=$(make show-var VARNAME=CONFIGURE_DIRS); cd $(make show-var VARNAME=WRKSRC); cd $build
    - make test

robotpkg-example-adder-16.04-release:
  <<: *robotpkg-example-adder
  image: memmos.laas.fr:5000/gepetto/example-adder/example-adder:16.04

doc-coverage:
  <<: *robotpkg-py-example-adder
  image: memmos.laas.fr:5000/gepetto/example-adder/py-example-adder:18.04
  before_script:
    - echo -e 'CXXFLAGS+= --coverage\nLDFLAGS+= --coverage\nPKG_DEFAULT_OPTIONS= debug' >> /opt/openrobots/etc/robotpkg.conf
  after_script:
    - cd /root/robotpkg/wip/py-example-adder
    - build=$(make show-var VARNAME=CONFIGURE_DIRS); cd $(make show-var VARNAME=WRKSRC); cd $build
    - make doc
    - mv doc/doxygen-html ${CI_PROJECT_DIR}
    - mkdir -p ${CI_PROJECT_DIR}/coverage/
    - gcovr -r .
    - gcovr -r . --html --html-details -o ${CI_PROJECT_DIR}/coverage/index.html
  artifacts:
    expire_in: 1 day
    paths:
      - doxygen-html/
      - coverage/

format:
  allow_failure: true
  image: gepetto/linters
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - test -f /builds/setup.cfg || ln -s /root/setup.cfg /builds
    - test -f /builds/.clang-format || ln -s /root/.clang-format /builds
  script:
    - check-clang-format.sh
    - flake8 .
    - yapf -dr .
