name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.laas.fr/tpillot/example-adder"
      env:
        GITLAB_HOSTNAME: "gitlab.laas.fr"
        GITLAB_USERNAME: "tpillot"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "717"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
